### ISSUE TITLE
Suggestion: On/Off Toggle

### ISSUE THREAD

**Issue by GiggliG** [ko-vasilev/hearthstone-autosquelch#1]
Several plugins have some settings in the plugins menu (not the plugins page in options). I think it would be a good idea to be able to toggle it on or off here. Sometimes I want to use this plugin, other times I am fine with emotes (playing friends for instance).

**Comment by ko-vasilev** [comment]
The thing is that the elements that are placed into Plugins section in navigation menu are simple buttons, no way of turning them into switches. I might open a window with a single switch inside of it, but at this stage it will be not that hard to go to settings and disable the plugin.

I might consider adding a setting to enable the plugin for different game modes (so you can turn off it for games vs friends).
