### ISSUE TITLE
Not able to detect autosquelch (v. 0.14.9)

### ISSUE THREAD

**Issue by excip** [ko-vasilev/hearthstone-autosquelch#2]
Hi

My Deck tracker version 0.14.9) is not able to detect autosquelch. Also I don't have a autosquelch.dll file like you mentioned if the installation is not working.

**Comment by ko-vasilev** [comment]
Hi. I think you downloaded incorrect archive. This is the correct one:
https://github.com/ko-vasilev/hearthstone-autosquelch/releases/download/0.1/Autosquelch.zip
