### ISSUE TITLE
Portable, but Plugns folder in AppData

### ISSUE THREAD

**Issue by blksith0** [ko-vasilev/hearthstone-autosquelch#7]
I've tried to make HDT portable (so I can put it all in my dropbox) by disabling the options to Save Data/Settings in Appdata. However what about the plugins folder? Is it possible to also make that read out of the local folder?
I don't really feel like making a symbolic link on every new device.

**Comment by ko-vasilev** [comment]
As I see right now, the HDT supports having plugins to be installed under the Plugins folder which located exactly where HDT executable is.
